### ISSUE TITLE
How to import My css to my app.js in main page 

### ISSUE THREAD

**Issue by Adii9669** [Adii9669/Chatapp#1]
<h1 >Problem </h1>
Hey Community I am new to  projects and this is my first project  i choose chat-app topic to go with and learn as i build I was able to import **_JSX-Bootstrapfile_** in app.js and now it is  visible but i am not able to import my **CSS** in app.js how can i Import **{css}** in my main app.js 
<br>

I am a Beginner  if you Can help in any way and i was looking for a guidance you can provide if possible would be so beneficial and more helpful to learn better for me . So that's all for now i will be  active now for asking out and   for completion of  this project.

**Comment by Der12kl** [comment]
@Adii9669  "Hi! I have already made changes to my app.js file to import the CSS. Please accept my pull request. I would appreciate your consideration. Thanks!"

**Comment by Adii9669** [comment]
> @Adii9669 "Hi! I have already made changes to my app.js file to import the CSS. Please accept my pull request. I would appreciate your consideration. Thanks!"

Hey can you help me to USE[https://mdbootstrap.com/docs/standard/extended/chat/#section-introduction](url) any of these bootstrap in react app and if possible can you tell me how to do  use the boot strap ?

**Comment by Der12kl** [comment]
Do you want me to make a chat (screenshot) that will work the same way?
![chat](https://github.com/Adii9669/Chatapp/assets/117436217/7f546402-82b1-43fa-8789-84b914859d17)
To use Bootstrap in your React app, you'll first need to install the Bootstrap package. You can do this by running the following command in your terminal:
npm install bootstrap
Next, you'll need to import Bootstrap's CSS file into your project. You can do this by adding the following line to your index.js or App.js file:
import 'bootstrap/dist/css/bootstrap.min.css';
Use Bootstrap classes in your JSX.
For additional styling, create a CSS file and connect it to the component.
To use Bootstrap React components, consider react-bootstrap or reactstrap.

**Comment by Adii9669** [comment]
> ootstrap/dist/css/bootstrap.min

Thanks for that I got it . I used the bootstrap Cdn link to my public index.html and script file from bootstrap website now the ui is working fine .
And now what should i do i know how to create a server/client server using **socket.io** in **_(Java)_**  how to should i use my **java socket files ** in react and how should i connect both ? 
Do you know how to do that?

**Comment by Der12kl** [comment]
"Thanks for your question! Here is an article that may help you understand the integration of Java sockets in a React application:  https://dev.to/fpeluso/a-simple-websocket-between-java-and-react-5c98 A simple WebSocket between Java and React. I hope you find it useful. If you have any further questions, feel free to ask !"
